Update: lint image job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -74,7 +74,14 @@ jobs:
           command: |
             sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
             sudo chmod +x /bin/hadolint
-            /bin/hadolint Dockerfile
+            /bin/hadolint Dockerfile | tee -a hadolint_lint.txt
+            lintErrors=$(stat -f%z hadolint_lint.txt)
+            if [ "$lintErrors" -gt "0" ]; then
+                echo "Errors found in the Dockerfile."
+                exit 1
+            else
+                echo "No errors were found in the Dockerfile."
+            fi
       - slack_notify_fail
   build_push_image:
     docker:
